export const tokens = {
  colors: {
    surface: '#131313',
    'surface-dim': '#131313',
    'surface-bright': '#393939',
    'surface-container-lowest': '#0e0e0e',
    'surface-container-low': '#1c1b1b',
    'surface-container': '#201f1f',
    'surface-container-high': '#2a2a2a',
    'surface-container-highest': '#353534',
    'on-surface': '#e5e2e1',
    'on-surface-variant': '#e0bfbd',
    'inverse-surface': '#e5e2e1',
    'inverse-on-surface': '#313030',
    outline: '#a78a88',
    'outline-variant': '#584140',
    'surface-tint': '#ffb3b0',
    primary: '#ffb3b0',
    'on-primary': '#68000f',
    'primary-container': '#ff6b6b',
    'on-primary-container': '#6d0010',
    'inverse-primary': '#ae2f34',
    secondary: '#ecb2ff',
    'on-secondary': '#520071',
    'secondary-container': '#6f258e',
    'on-secondary-container': '#e59dff',
    tertiary: '#52dea2',
    'on-tertiary': '#003824',
    'tertiary-container': '#00b179',
    'on-tertiary-container': '#003b26',
    error: '#ffb4ab',
    'on-error': '#690005',
    'error-container': '#93000a',
    'on-error-container': '#ffdad6',
    'primary-fixed': '#ffdad8',
    'primary-fixed-dim': '#ffb3b0',
    'on-primary-fixed': '#410006',
    'on-primary-fixed-variant': '#8c1520',
    'secondary-fixed': '#f8d8ff',
    'secondary-fixed-dim': '#ecb2ff',
    'on-secondary-fixed': '#320047',
    'on-secondary-fixed-variant': '#6c228c',
    'tertiary-fixed': '#72fbbc',
    'tertiary-fixed-dim': '#52dea2',
    'on-tertiary-fixed': '#002113',
    'on-tertiary-fixed-variant': '#005236',
    background: '#131313',
    'on-background': '#e5e2e1',
  },
  typography: {
    displayLg: {
      fontFamily: 'Inter',
      fontSize: 64,
      fontWeight: '800' as const,
      lineHeight: 70,
      letterSpacing: -2.56,
    },
    headlineXl: {
      fontFamily: 'Inter-Bold',
      fontSize: 40,
      fontWeight: '700' as const,
      lineHeight: 48,
      letterSpacing: -0.8,
    },
    headlineXlMobile: {
      fontFamily: 'Inter-Bold',
      fontSize: 32,
      fontWeight: '700' as const,
      lineHeight: 38,
    },
    headlineMd: {
      fontFamily: 'Inter-SemiBold',
      fontSize: 24,
      fontWeight: '600' as const,
      lineHeight: 33.6,
    },
    bodyLg: {
      fontFamily: 'Inter',
      fontSize: 18,
      fontWeight: '400' as const,
      lineHeight: 28.8,
    },
    bodyMd: {
      fontFamily: 'Inter',
      fontSize: 16,
      fontWeight: '400' as const,
      lineHeight: 24,
    },
    labelCaps: {
      fontFamily: 'Space Grotesk-SemiBold',
      fontSize: 12,
      fontWeight: '600' as const,
      lineHeight: 14.4,
      letterSpacing: 1.2,
      textTransform: 'uppercase' as const,
    },
    technicalData: {
      fontFamily: 'Space Grotesk',
      fontSize: 14,
      fontWeight: '500' as const,
      lineHeight: 19.6,
    },
  },
  spacing: {
    unit: 4,
    containerMarginMobile: 20,
    containerMarginDesktop: 80,
    gutter: 16,
    stackSm: 8,
    stackMd: 24,
    stackLg: 48,
  },
  rounded: {
    sm: 4,
    default: 8,
    md: 12,
    lg: 16,
    xl: 24,
    full: 9999,
  },
};
